apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskboard-api
  labels:
    app: taskboard-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskboard-api
  template:
    metadata:
      labels:
        app: taskboard-api
    spec:
      containers:
      - name: taskboard-api
        image: taskboard-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5100
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: TASKS_SERVICE_URL
          value: "http://tasks-service:8082"
